package com.common.entity;

import java.io.Serializable;
import java.util.Date;

public class OauthSystemResource extends Base implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth_system_resource
     *
     * @mbg.generated Tue Aug 01 19:04:01 CST 2017
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_system_resource.oauth_system_resource_id
     *
     * @mbg.generated Tue Aug 01 19:04:01 CST 2017
     */
    private Integer oauthSystemResourceId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_system_resource.system_id
     *
     * @mbg.generated Tue Aug 01 19:04:01 CST 2017
     */
    private Integer systemId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_system_resource.resource_id
     *
     * @mbg.generated Tue Aug 01 19:04:01 CST 2017
     */
    private Integer resourceId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_system_resource.create_time
     *
     * @mbg.generated Tue Aug 01 19:04:01 CST 2017
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_system_resource.update_time
     *
     * @mbg.generated Tue Aug 01 19:04:01 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_system_resource.oauth_system_resource_id
     *
     * @return the value of oauth_system_resource.oauth_system_resource_id
     * @mbg.generated Tue Aug 01 19:04:01 CST 2017
     */
    public Integer getOauthSystemResourceId() {
        return oauthSystemResourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_system_resource.oauth_system_resource_id
     *
     * @param oauthSystemResourceId the value for oauth_system_resource.oauth_system_resource_id
     * @mbg.generated Tue Aug 01 19:04:01 CST 2017
     */
    public void setOauthSystemResourceId(Integer oauthSystemResourceId) {
        this.oauthSystemResourceId = oauthSystemResourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_system_resource.system_id
     *
     * @return the value of oauth_system_resource.system_id
     * @mbg.generated Tue Aug 01 19:04:01 CST 2017
     */
    public Integer getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_system_resource.system_id
     *
     * @param systemId the value for oauth_system_resource.system_id
     * @mbg.generated Tue Aug 01 19:04:01 CST 2017
     */
    public void setSystemId(Integer systemId) {
        this.systemId = systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_system_resource.resource_id
     *
     * @return the value of oauth_system_resource.resource_id
     * @mbg.generated Tue Aug 01 19:04:01 CST 2017
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_system_resource.resource_id
     *
     * @param resourceId the value for oauth_system_resource.resource_id
     * @mbg.generated Tue Aug 01 19:04:01 CST 2017
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_system_resource.create_time
     *
     * @return the value of oauth_system_resource.create_time
     * @mbg.generated Tue Aug 01 19:04:01 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_system_resource.create_time
     *
     * @param createTime the value for oauth_system_resource.create_time
     * @mbg.generated Tue Aug 01 19:04:01 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_system_resource.update_time
     *
     * @return the value of oauth_system_resource.update_time
     * @mbg.generated Tue Aug 01 19:04:01 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_system_resource.update_time
     *
     * @param updateTime the value for oauth_system_resource.update_time
     * @mbg.generated Tue Aug 01 19:04:01 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}